dist : focal
language: node_js
node_js:
  - "node"
  - "14"
  - "13"
  - "12"
#  - "11" (lack private class fields)
#  - "10"
#  - "9" (doesn't have NODE_MODULE_INIT’, AddEnvironmentCleanupHook ); also lacks TLS 1.3
#  - "8"
#  - "7" (doesn't have Utf8Value with isolate, 12 doesn't have Utf8Value without isolate())
#  - "6"
#  - "5"
#  - "4"

matrix:
  include:
    - os : windows
    - os : linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - uuid-dev
            - python3
    - os : mac
#os:
#  - windows
#  - linux
#  - osx

#compiler:
#  - gcc

#env:

#if: NOT branch = master
#if: NOT tag =~ ^[0-9]*.[0-9]*.[0-9]*

branches:
  only:
    - /^[0-9]+\.[0-9]+.[0-9]+/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8784d70ae92882b8923a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

