
var vfs = require( ".." );

var ids = [];
for( var n = 0; n < 10; n++ )
	ids[n] = vfs.id();
console.log( "Some IDs:", ids );

var now = Date.now();
var n = 0;
const length = 3000;

while( ( (n%100) !== 0 ) || (( Date.now() - now ) < length) )
{
	vfs.id();
	n++;
}
console.log( `Generated ${n}(${n/length}/ms) in ${length/1000} seconds`  );


var key = {key:ids[0], step:0} ;
var tmp = "some sample String %@!()*)(%";
var tmp2 = vfs.u8xor( tmp, key );
key.step = 0;
var tmp3 = vfs.u8xor( tmp2, key );

console.log( "ENcoder test of :", "source:", tmp, "encode:", tmp2,  "decode:", tmp3 );


const runlength = 1000;
var key = {key:vfs.id(), step:0 };


var packets = [ '{short packet 1}' 
	      , '{longer pakcet, but still pretty short, maybe just a few arguments}'
	      , '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
	      , '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
	      , '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
               + '[{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}][{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments},{MUCH longer pakcet, but still pretty short, maybe just a few arguments}]'
	      ];

packets.forEach( p=>{
	var now = Date.now();
	var n = 0;
	var s = key.step;
	var tst = vfs.u8xor( p, key );
	key.step = s;
	var tst2 = vfs.u8xor( tst, key );
	key.step = s;
	if( tst2 !== p ) 
		throw new Error( ["String did not recode correctly:\n", p, "\n", tst, "\n", tst2].join() );

	while( ( n % 100 !== 0) || ( (Date.now() - now) < runlength) ) {
		n++;
		vfs.u8xor( p, key );
	}
	console.log( `encoded length ${p.length} = ${n}(${n/runlength}/ms) in ${runlength/1000} seconds (${n*p.length/runlength} chars/ms)` );
} );